name: Build Python Image
run-name: ${{ gitea.actor }} builds new python docker image
on: [ push ]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: gitea.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v4
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."git.prod.maki-it.de"]
      - name: Build and push Docker image
        uses: https://github.com/docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "git.prod.maki-it.de/${{ gitea.repository }}:${{gitea.sha}},git.prod.maki-it.de/${{ gitea.repository }}:latest"
