name: Build Python Image
run-name: ${{ github.actor }} builds new python docker image
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: git.prod.maki-it.de/${{ github.repository }}
          flavor: |
            latest=auto
          tags: |
            type=raw,value=debian
            type=ref,event=branch,prefix=debian-
            type=ref,event=pr,prefix=debian-
            type=semver,pattern={{version}},prefix=debian-
            type=semver,pattern={{major}}.{{minor}},prefix=debian-
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/0.') }},prefix=debian-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./debian.Dockerfile
          build-args: |
            BASE_NAME=${{github.repository}}:debian
            BUILDTIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
            SOURCE_URL=${{ github.server_url }}/${{ github.repository }}
          platforms: |
            linux/amd64
            linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.meta.outputs.tags }}
