name: Build Python Image
run-name: ${{ github.actor }} builds new python docker image
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Python Version from Dockerfile
        id: get-python-version
        shell: bash
        run: |
          if [[ $(grep -oP '(?<=^FROM python:)[0-9.]*' debian.Dockerfile) =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            echo "MAJOR=${BASH_REMATCH[1]}" >> $GITHUB_ENV
            echo "MINOR=${BASH_REMATCH[2]}" >> $GITHUB_ENV
            echo "PATCH=${BASH_REMATCH[3]}" >> $GITHUB_ENV
            echo "SEMVER=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV
          else
            exit -1
          fi

      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=raw,value=debian
            type=raw,prefix=debian-,value=${{ env.MAJOR }}
            type=raw,prefix=debian-,value=${{ env.MAJOR }}.${{ env.MINOR }}
            type=raw,prefix=debian-,value=${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}

      - name: Debug metadata
        run: |
          echo "Image: ${{ steps.meta.outputs.json }}"
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "Labels: ${{ steps.meta.outputs.labels }}"
          echo "Test. "${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}""

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./debian.Dockerfile
          annotations: |
            org.opencontainers.image.base.title=Python ${{ env.SEMVER }} on Debian
            org.opencontainers.image.base.description=Python ${{ env.SEMVER }} on Debian with non-root user
            org.opencontainers.image.base.authors=Maki IT <kontakt@maki-it.de>
            org.opencontainers.image.base.version=${{ env.SEMVER }}
            org.opencontainers.image.base.revision=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
            org.opencontainers.image.base.created=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            org.opencontainers.image.base.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.base.name=${{github.repository}}:debian
            org.opencontainers.image.title=Python ${{ env.SEMVER }} on Debian
            org.opencontainers.image.description=Python ${{ env.SEMVER }} on Debian with non-root user
            org.opencontainers.image.authors=Maki IT <kontakt@maki-it.de>
            org.opencontainers.image.version=${{ env.SEMVER }}
            org.opencontainers.image.revision=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
            org.opencontainers.image.created=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.name=${{github.repository}}:debian
          platforms: |
            linux/amd64
            linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.meta.outputs.tags }}
          provenance: false  # Fix for unknown/unknown image build
          cache-from: type=gha
          cache-to: type=gha,mode=max
