name: Test Python Image
run-name: ${{ github.actor }} tests new python docker image
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - .gitignore
      - .editorconfig
      #- .github/**
      - .vscode/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build local Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./debian.Dockerfile
          load: true
          tags: test

      - name: Test Docker image
        run: |
          docker run --rm test python -V 
